### ISSUE TITLE
hey in your code  assignment you not add ".py" extension 

### ISSUE THREAD

**Issue by ombharamadev** [afiyamujar/day_1#1]
hey in your code  assignment you not add ".py" extension  so that why you got 4 marks

**Comment by afiyamujar** [comment]
Thank you sir I will make sure to not repeat this again!

**Comment by ombharamadev** [comment]
please update the file name and add .py in last of every file i already increase your marks 4 to 6 marks please updated the repo data

**Comment by afiyamujar** [comment]
Thank you sir
